# Generated by Django 3.0.8 on 2021-11-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoelectrodomestico',
            name='rangoPrecios',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
